import Head from 'next/head'
import Link from 'next/link'

export default function Header() {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        Header
        <br/>
        <Link href="/person/1" as="/person/1">
          person/1
        </Link>
  
      </div>
    )
  }
  